# Generated by Django 6.0.6 on 2026-06-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temperatura_max_ideal', models.FloatField(default=24.0)),
                ('humedad_max_ideal', models.FloatField(default=60.0)),
                ('tiempo_limpieza_max_horas', models.IntegerField(default=4)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='cocina.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='MetricasActuales',
            fields=[
                ('zona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metricas_actuales', serialize=False, to='cocina.zona')),
                ('humedad', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('residuos', models.FloatField()),
                ('ultima_limpieza', models.DateTimeField()),
                ('integridad_estructural', models.CharField(default='OK', max_length=20)),
                ('score_riesgo', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMetricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('residuos', models.FloatField()),
                ('integridad_estructural', models.CharField(max_length=20)),
                ('score_riesgo', models.IntegerField()),
                ('capturado_en', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='cocina.zona')),
            ],
            options={
                'ordering': ['-capturado_en'],
            },
        ),
    ]
